[project]
name = "marimo-themes"
version = "0.1.0"
description = "A library of themes for marimo notebook"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["marimo>=0.9.14"]

[tool.uv]
dev-dependencies = ["marimo>=0.9.14"]
